apiVersion: v1
kind: Service
metadata:
  name: subscription-backend-svc
spec:
  selector:
    app: subscription-backend
  ports:
    - name: http
      protocol: TCP
      port: 1398
      targetPort: 1398
