apiVersion: v1
kind: Service
metadata:
  name: audio-storage-backend-svc
spec:
  selector:
    app: audio-storage-backend
  ports:
    - name: http
      protocol: TCP
      port: 1398
      targetPort: 1398
