apiVersion: v1
kind: Service
metadata:
  name: audio-streaming-backend-svc
spec:
  selector:
    app: audio-streaming-backend
  ports:
    - name: http
      protocol: TCP
      port: 1398
      targetPort: 1398
