# 첫 번째 단계: Next.js 애플리케이션 빌드
FROM node:alpine as builder

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 설치
COPY package*.json ./
RUN npm install

# 소스 코드 복사 및 애플리케이션 빌드
COPY ./ ./
RUN npm run build

# 두 번째 단계: Nginx로 애플리케이션 배포
FROM nginx

# Next.js 애플리케이션 복사
COPY --from=builder /app/out /usr/share/nginx/html

# Nginx 설정 파일 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 80번 포트 열기
EXPOSE 80

# Nginx 서버 실행
CMD ["nginx", "-g", "daemon off;"]
