apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-storage-backend
  labels:
    app: audio-storage-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-storage-backend
  template:
    metadata:
      labels:
        app: audio-storage-backend
    spec:
      containers:
        - name: server
          image: softho0n/audio-storage-backend-app:v3
          ports:
            - containerPort: 1398
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/credentials.json
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-creds
