apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-backend
  labels:
    app: payments-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-backend
  template:
    metadata:
      labels:
        app: payments-backend
    spec:
      containers:
        - name: server
          image: softho0n/payments-backend-app:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 1398
