apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-backend
  labels:
    app: user-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-backend
  template:
    metadata:
      labels:
        app: user-backend
    spec:
      containers:
        - name: server
          image: softho0n/user-backend-app:v3
          ports:
            - containerPort: 1398
