apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-streaming-backend
  labels:
    app: audio-streaming-backend
    version: risky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-streaming-backend
      version: risky
  template:
    metadata:
      labels:
        app: audio-streaming-backend
        version: risky
    spec:
      containers:
        - name: server
          image: softho0n/audio-streaming-backend-app-risky:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1398
