apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-deployment
  labels:
    app: backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: softho0n/backoffice-app:v1
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/credentials.json
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-creds
