apiVersion: v1
kind: Service
metadata:
  name: backoffice-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
    - name: streamlit-port
      protocol: TCP
      targetPort: 8501
      port: 8501
