apiVersion: v1
kind: Service
metadata:
  labels:
    app: subscription-mongo
  name: subscription-mongo-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: subscription-mongo
  clusterIP: None
