apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-backend
  labels:
    app: user-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-backend
  template:
    metadata:
      labels:
        app: user-backend
    spec:
      containers:
        - name: server
          image: softho0n/user-backend-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1398
---
apiVersion: v1
kind: Service
metadata:
  name: user-backend-svc
spec:
  selector:
    app: user-backend
  ports:
    - name: http
      protocol: TCP
      port: 1398
      targetPort: 1398
