apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-deployment
  labels:
    app: backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: softho0n/backoffice-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 745Mi
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/credentials.json
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-creds
---
apiVersion: v1
kind: Service
metadata:
  name: backoffice-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - name: streamlit-port
      protocol: TCP
      port: 8501
      nodePort: 30010
